gfmultiplication: main.cpp modulus.cpp multiplication.cpp addition.cpp
	g++ -o gfmultiplication main.cpp modulus.cpp multiplication.cpp addition.cpp
	echo "Compiling GFMultiplication"
	
@all:
	echo "Done"
