gfmultiplication: main.cpp modulus.cpp multiplication.cpp addition.cpp
	g++ -o gfmultiplication main.cpp modulus.cpp multiplication.cpp addition.cpp
	@echo "Compiling GFMultiplication"


test: gfmultiplication
	./gfmultiplication 10110110101 1101110 14
	
all:
	@echo "Test passed!"
